export const businessConfig = {
  name: 'Tenda do Ozi Gastrobar',
  tagline: 'Espetos, petiscos e bebidas para curtir bons momentos.',
  minimumOrder: 15,
  whatsappNumber: '5511999999999',
  address: 'Av. Pres. Vargas, 833 - Jardim Nova Itapevi, Itapevi - SP, 06694-000, Brasil',
  deliveryTime: '50 - 70 minutos',
  hours: 'Quarta a sabado, das 18:30 as 23:00',
  openingHours: [
    { day: 'Domingo', time: 'Fechado' },
    { day: 'Segunda', time: 'Fechado' },
    { day: 'Terça', time: 'Fechado' },
    { day: 'Quarta', time: '18:30 - 23:00' },
    { day: 'Quinta', time: '18:30 - 23:00' },
    { day: 'Sexta', time: '18:30 - 23:00' },
    { day: 'Sábado', time: '18:30 - 23:00' },
  ],
  paymentMethods: [
    'Dinheiro',
    'PIX (chave exibida apos o envio)',
    'Cartão de Débito - Maquininha',
    'Cartão de Crédito - Maquininha',
    'Vale Refeição / Alimentação',
    'Transferência Eletrônica',
    'Transferencia Nubank',
    'Visa',
    'MasterCard',
    'Elo',
  ],
  googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.%20Pres.%20Vargas%20833%20Jardim%20Nova%20Itapevi%20Itapevi%20SP%2006694-000%20Brasil',
  googleMapsEmbedUrl: 'https://www.google.com/maps?q=Av.%20Pres.%20Vargas%20833%20Jardim%20Nova%20Itapevi%20Itapevi%20SP%2006694-000%20Brasil&output=embed',
  instagramUrl: 'https://www.instagram.com/',
  facebookUrl: 'https://www.facebook.com/',
  paymentNote: 'Pagamento online sera integrado em uma proxima versao.',
}
